name: Push Notification to Discord

on:
  push:
    branches:
      - main  # يعمل عند أي تعديل على الفرع الرئيسي

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Get Changed Files from GitHub API
        id: changed-files
        run: |
          FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" \
            | jq -r '.files[].filename' | tr '\n' ' ')
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Format Commit Timestamp
        id: format-time
        run: |
          FORMATTED_TIME=$(date -u -d "${{ github.event.head_commit.timestamp }}" "+%A, %B %d, %Y at %I:%M %p UTC" 2>/dev/null || date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "${{ github.event.head_commit.timestamp }}" "+%A, %B %d, %Y at %I:%M %p UTC")
          echo "FORMATTED_TIME=$FORMATTED_TIME" >> $GITHUB_ENV

      - name: Send Notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          FILES_FORMATTED=$(echo "${{ env.FILES }}" | tr ' ' '\n')
          MESSAGE="🚀 **Files have been modified!**\n👤 **User:** ${{ github.actor }}\n📂 **Modified files:**\n\`\`\`${FILES_FORMATTED}\`\`\`\n⏰ **Time:** ${{ env.FORMATTED_TIME }}"

          PAYLOAD=$(jq -n --arg msg "$MESSAGE" '{username: "GitHub Actions", content: $msg}')
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL"
